# Generated by Django 4.1.5 on 2023-05-25 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingbackend', '0002_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.TextField(),
        ),
    ]
