# Generated by Django 4.1.5 on 2023-05-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingbackend', '0003_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(),
        ),
    ]
