# Generated by Django 4.1.5 on 2023-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingbackend', '0008_booking_activity_booking_pilot_booking_tug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tug',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
