# Generated by Django 4.1.5 on 2023-06-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingbackend', '0009_alter_booking_tug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
